Fix NVMe Gen number
system76/tech-docs pull request #155
Opened 2022-11-15 19:44 UTC by ahoneybun

2022-11-15 19:50 UTC, n3m0-22 approved these changes

2022-11-22 20:48 UTC, jacobgkau requested changes
The readme (spec list) indicates that Gen 2 is the correct number. If this is actually wrong, then the readme would also need to be updated.

2022-11-22 20:50 UTC, ahoneybun commented
> The readme (spec list) indicates that Gen 2 is the correct number. If this is actually wrong, then the readme would also need to be updated.

I put a Gen 3 drive in the lab unit the other day for testing the backlight issue on this model and it worked without issue. I'll update the README as well.

2022-11-22 20:59 UTC, jacobgkau requested changes
We already tested speeds to confirm that Gen 2 is correct: https://github.com/system76/tech-docs/pull/34 

This update is inaccurate.

2022-11-28 23:29 UTC, closed without merging