Copy image from mira-r3 for the Thelio Io button
system76/tech-docs pull request #173
Opened 2023-04-21 16:09 UTC by ahoneybun

This image is missing from major-r3 tech docs so copied it from mira-r3.

2023-04-24 23:43 UTC, jacobgkau requested changes
We shouldn't use a mira-r3 photo in the major-r3 section. I'll check if I have a photo for this, or try to get one if not.

2023-04-24 23:48 UTC, leviport commented
Here's a quick one, just for comparison, of major-r3. Since the thelio-IO and drive cage mounting points are pretty much the same between mira-r3 and major-r3, I don't think the difference is enough for it to matter.

![IMG_20230424_174624_835](https://user-images.githubusercontent.com/13512097/234139044-a988c17f-3ca2-430b-a478-3c5405370360.jpg)

2023-04-25 00:56 UTC, jacobgkau commented
I found the photos I took for this purpose while shooting.

2023-04-25 01:01 UTC, jacobgkau approved these changes

2023-04-25 01:01 UTC, merged