thelio-astra-a1-n4
system76/tech-docs pull request #263
Opened 2024-09-05 20:47 UTC by jackpot51

2024-09-06 22:05 UTC, jacobgkau reviewed
Here are the points we hit while going through this guide. Most of our issues had to do with `apt-get` commands randomly hanging while we were running them in the BMC SOL console, which happened twice.

2024-12-30 23:12 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- On the `Guided storage configuration` page, select `Use an entire disk`, and choose the desired disk. Select `Done` to continue.
I've added a note to leave the `Set up this disk as an LVM group` option enabled.

2024-12-30 23:14 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +sudo apt-get dist-upgrade
I've changed all instances of `dist-upgrade` to `full-upgrade` and all instances of `apt-get` to `apt`.

2024-12-30 23:16 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- The system will boot to a terminal login prompt. Log in with `system76` as the username and `system76` as the password.
I've added a note that you may need to log in with the BMC serial console if the physical display does not show a prompt.

2024-12-30 23:17 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- Disable and mask systemd-networkd services with the following commands:
I've indented those three networking-related points.

2024-12-30 23:22 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- There is a jumper labeled `BMC disable` that can bypass the requirement that the BMC boots before the power button is functional.
I've added a note that it's not recommended to disable the BMC until after initial setup is complete. I've also specified which pins on the jumper need to be bridged per the motherboard manual.

2024-12-30 23:24 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- You should see a login screen, where you can log in to the `System76` user with the password `system76`.
Since we got no further guidance about this, I've added a note to try a different connection type and/or display if the login screen doesn't appear.

2024-12-30 23:26 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +sudo apt-get install system76-driver
Not adding a note to avoid incorrect info since we received no further guidance on this.

2024-12-30 23:27 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- Additional ethernet connections will repeatedly fail to connect. Open `nm-connnection-editor` to remove them.
Changed to the suggested wording.

2024-12-30 23:28 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +sudo apt-get dist-upgrade
Changed all instances of `dist-upgrade` to `full-upgrade`.

2024-12-31 19:02 UTC, leviport requested changes
A couple small things, but otherwise looks great!

2024-12-31 19:12 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/internal-overview.md
> +    - Connect to power supply
It's multiple connectors, so they connect to the power supply.

2024-12-31 19:16 UTC, leviport commented on src/models/thelio-astra-a1-n1/internal-overview.md
> +    - Connect to power supply
Ah, I see now. The two singular "connector" instances in the line above it tripped me up. Disregard this comment.

2024-12-31 19:22 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/repairs.md
> +3. Unscrew the four back thumbscrews and two top crossbar screws holding the CPU duct in place.
Fixed in ad3d5b072f949008ffd737cd02262839e1149381.

2024-12-31 19:22 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/repairs.md
> +3. If you are replacing the CMOS battery, pull it away from the SFP port casing.
Fixed in ad3d5b072f949008ffd737cd02262839e1149381.

2024-12-31 19:22 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/repairs.md
> +5. Plug in the new CMOS battery (or re-connect the existing CMOS battery) and adhere it to the top of the SFP port casing.
Fixed in ad3d5b072f949008ffd737cd02262839e1149381.

2024-12-31 19:22 UTC, jacobgkau commented on src/models/thelio-astra-a1-n1/ubuntu-24.04.md
> +- Download the [Ubuntu Server for ARM 24.04.1 LTS ISO](https://cdimage.ubuntu.com/releases/24.04/release/ubuntu-24.04.1-live-server-arm64.iso).
Fixed in ad3d5b072f949008ffd737cd02262839e1149381.

2024-12-31 19:25 UTC, leviport approved these changes

2024-12-31 21:13 UTC, merged