Thelio Major R5-N3
system76/tech-docs pull request #270
Opened 2024-10-19 01:27 UTC by jacobgkau

This adds the Thelio Major R5-N3 (thelio-major-r5-n3) to tech docs.

WIP.

2024-10-22 23:25 UTC, jacobgkau commented
This is finished other than needing to confirm the GPU clearance with mechanical engineering.

2024-10-23 17:27 UTC, leviport requested changes
I found a few small problems, but this otherwise looks excellent!

2024-10-23 17:27 UTC, leviport commented on src/models/thelio-major-r5-n3/repairs.md
> +9. Screw the three Torx screws back into place.
I think the screw torque order (1-2-3) should be mentioned in the tightening directions

2024-10-23 17:27 UTC, leviport commented on src/models/thelio-major-r5-n3/repairs.md
> +    - The RAM stick will only fit in one direction. The larger group of pins goes on top.
Should "top" be changed to either left or right, since the RAM slots are horizontal?

2024-10-23 17:27 UTC, leviport commented on src/models/thelio-major-r5-n3/repairs.md
> +    ![RAM slot order](./img/ram-order.webp)
Image link is broken

2024-10-23 17:37 UTC, jacobgkau commented on src/models/thelio-major-r5-n3/README.md
> +        - [Kinsington KF556R28RBE2K4]() (32GB/stick)
Hynix doesn't seem to have the first three SKUs listed on their [product page](https://product.skhynix.com/products/dram/module.go) (although I see resellers offering them, so they are real SKUs). I'm going to need to just remove the links for the Hynix ones.

2024-10-23 17:39 UTC, jacobgkau commented on src/models/thelio-major-r5-n3/repairs.md
> +**Tools required:** Cross-head (Phillips) screwdriver (optional)
Sad

2024-10-23 17:50 UTC, jacobgkau commented on src/models/thelio-major-r5-n3/repairs.md
> +![M.2 slots](./img/m2-slots.webp)
Confirmed it's Gen 4 & fixed the graphic.

2024-10-23 19:28 UTC, leviport approved these changes
:metal:

2024-10-23 21:28 UTC, merged