Add darp7
system76/tech-docs pull request #54
Opened 2021-01-19 22:03 UTC by jacobgkau

This PR:
- Adds the Darter Pro 7 to tech docs, including tech specs, external overview, internal overview, and service manual.
- Makes a couple of small typo/wording tweaks in darp6 and meer5.

2021-01-20 16:42 UTC, bflanagin requested changes
In "Steps to remove the bottom cover"
perimiter needs to be changed to perimeter

Everything else looks good beyond that.

2021-01-20 17:51 UTC, jacobgkau commented
Fixed with 723f61d5b65d4a3b2f7d9f9f52771e61c2e32af5, thanks for catching that.

2021-01-20 18:01 UTC, bflanagin approved these changes

2021-01-21 19:22 UTC, ahoneybun approved these changes
Everything looks fantastic as usual!

2021-01-21 19:25 UTC, merged