Add note about work surface & revise battery removal steps
system76/tech-docs pull request #69
Opened 2021-03-25 18:24 UTC by jacobgkau

__Add note about work surface to all applicable models:__

Support requested we add this written detail to address feedback from a customer who scratched up his/her laptop while working on it.

Criteria for adding:
- Any section that requires having the laptop turned upside-down gets the note, except...
- Any section that links to a previous section with the note _before_ requiring to turn the laptop upside-down does not need the note repeated.

__Revise battery removal instructions for lemp9/lemp10/darp7:__

This PR also adds a more detailed and hopefully less confusing description about how to remove the battery from systems where it's held in with adhesive. (There are no tabs holding the battery in place; there are tabs sticking out from the tape underneath the battery.)

2021-03-25 18:32 UTC, bflanagin approved these changes

2021-03-25 19:42 UTC, bflanagin requested changes
I changed some of the instances of perimiter to perimeter. Might want to do a quick once over to make sure I didn't miss any. Everything else reads well.

2021-03-25 22:24 UTC, jacobgkau commented
Thanks for catching that! Considering how uptight I am about grammar, I am embarrassingly bad at spelling without a spellchecker.

2021-03-26 11:39 UTC, bflanagin approved these changes

2021-03-26 14:39 UTC, merged